### ISSUE TITLE
Cannot read properties of null (reading 'swagger')

### ISSUE THREAD

**Issue by hf-kklein** [thiyagu06/openapi-validator-action#3]
The error message is:

> Run thiyagu06/openapi-validator-action@v1
file path ./open_api_specs/openapi.json
schema file full path:/home/runner/work/my_repo_name/my_repo_name/open_api_specs/openapi.json
Cannot read properties of null (reading 'swagger')

The Action yml is:
```yml
name: Foo
on: push
jobs:
  check:
    name: Check All
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["./open_api_specs/openapi.json"]
    steps:
      - name: "validate openapi schema ${{matrix.path}}"
        uses: thiyagu06/openapi-validator-action@v1
        with:
          filepath: "${{matrix.path}}"
```
